---
apiVersion: v1
kind: Service
metadata:
  name: coupon-bot
  namespace: coupon-test
  labels:
    coupon-ci: transient
spec:
  selector:
    app: coupon-bot
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
