name: "Coupon: Deploy"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/BotInfra/**'
      - 'src/CouponHubBot/**'
      - 'src/coupon-hub-bot/**'
      - 'src/Dockerfile.bot'
      - 'tests/CouponHubBot.Tests/**'
      - 'tests/CouponHubBot.Ocr.Tests/**'
      - 'tests/BotTestInfra/**'
      - 'tests/FakeTgApi/**'
      - 'tests/FakeAzureOcrApi/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'global.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_bot-deploy.yml
    with:
      test-command: |
        dotnet test tests/CouponHubBot.Tests/CouponHubBot.Tests.fsproj -c Release --logger "trx;LogFileName=test-results.trx"
        dotnet test tests/CouponHubBot.Ocr.Tests/CouponHubBot.Ocr.Tests.fsproj -c Release --logger "trx;LogFileName=test-results.trx"
      migrations-path: src/coupon-hub-bot/migrations
      docker-image: ghcr.io/szer/coupon-bot
      bot-project: CouponHubBot
      argocd-app-name: coupon-bot
      container-name: coupon-bot
    secrets:
      WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}
      DB_PROD_URL: ${{ secrets.COUPON_DB_PROD_URL }}
      DB_PROD_USERNAME: ${{ secrets.COUPON_DB_PROD_USERNAME }}
      DB_PROD_PASSWORD: ${{ secrets.COUPON_DB_PROD_PASSWORD }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
