name: "Coupon: Build"

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_bot-build.yml
    with:
      test-command: |
        dotnet test tests/CouponHubBot.Tests/CouponHubBot.Tests.fsproj -c Release --logger "trx;LogFileName=test-results.trx" --logger "console;verbosity=detailed"
        dotnet test tests/CouponHubBot.Ocr.Tests/CouponHubBot.Ocr.Tests.fsproj -c Release --logger "trx;LogFileName=test-results.trx" --logger "console;verbosity=detailed"
      paths-filter: |
        relevant:
          - 'src/BotInfra/**'
          - '!src/BotInfra/**/*.md'
          - 'src/CouponHubBot/**'
          - '!src/CouponHubBot/**/*.md'
          - 'src/Dockerfile.bot'
          - 'tests/CouponHubBot.Tests/**'
          - 'tests/CouponHubBot.Ocr.Tests/**'
          - 'tests/BotTestInfra/**'
          - 'tests/FakeTgApi/**'
          - 'tests/FakeAzureOcrApi/**'
          - 'Directory.Build.props'
          - 'Directory.Packages.props'
          - 'global.json'
