name: "Vahter: Build"

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/BotInfra/**'
      - 'src/VahterBanBot/**'
      - 'src/Dockerfile.bot'
      - 'tests/VahterBanBot.Tests/**'
      - 'tests/BotTestInfra/**'
      - 'tests/FakeTgApi/**'
      - 'tests/FakeAzureOcrApi/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'global.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Tests
      run: dotnet test tests/VahterBanBot.Tests/VahterBanBot.Tests.fsproj -c Release --logger "trx;LogFileName=test-results.trx" --logger "console;verbosity=detailed"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/*.trx"
      if: ${{ always() }}

    - name: Upload container logs
      uses: actions/upload-artifact@v4
      with:
        name: container-logs
        path: test-artifacts/
      if: ${{ always() }}
