name: "Vahter: Deploy"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/BotInfra/**'
      - 'src/VahterBanBot/**'
      - 'src/vahter-bot/**'
      - 'src/Dockerfile.bot'
      - 'tests/VahterBanBot.Tests/**'
      - 'tests/BotTestInfra/**'
      - 'tests/FakeTgApi/**'
      - 'tests/FakeAzureOcrApi/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'global.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_bot-deploy.yml
    with:
      test-command: >-
        dotnet test tests/VahterBanBot.Tests/VahterBanBot.Tests.fsproj
        -c Release --logger "trx;LogFileName=test-results.trx"
        --logger "console;verbosity=detailed"
      migrations-path: src/vahter-bot/migrations
      db-name: vahter_db_v2
      docker-image: ghcr.io/fsharplang-ru/vahter-bot
      bot-project: VahterBanBot
      argocd-app-name: vahter-bot
      container-name: vahter-bot
    secrets:
      WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}
      DB_PROD_HOST: ${{ secrets.DB_PROD_HOST }}
      DB_PROD_USERNAME: ${{ secrets.DB_PROD_USERNAME }}
      DB_PROD_PASSWORD: ${{ secrets.DB_PROD_PASSWORD }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
